#ifndef ProtectedConfig_h
#define ProtectedConfig_h
// Core binary integrity hashes - REPLACE with actual values after building CoreTelemetry
#define FMCORE_TEXT_SHA256_A @"PLACEHOLDER_REPLACE_WITH_ACTUAL_HASH"
#define FMCORE_EXPORT_SHA256_A @"PLACEHOLDER_REPLACE_WITH_ACTUAL_HASH"
#define FMCORE_SECTION_SHA256_A @"PLACEHOLDER_REPLACE_WITH_ACTUAL_HASH"
#define FMCORE_TEXT_SHA256_B @"PLACEHOLDER_REPLACE_WITH_ACTUAL_HASH"
#define FMCORE_EXPORT_SHA256_B @"PLACEHOLDER_REPLACE_WITH_ACTUAL_HASH"
#define FMCORE_SECTION_SHA256_B @"PLACEHOLDER_REPLACE_WITH_ACTUAL_HASH"
#endif
